// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQl6AFfSwDTGTsHnOs2yPuuzbrbMHH96c',
    appId: '1:855525575269:web:18178a8cb0935c2583148c',
    messagingSenderId: '855525575269',
    projectId: 'student-management-app-c937e',
    authDomain: 'student-management-app-c937e.firebaseapp.com',
    storageBucket: 'student-management-app-c937e.firebasestorage.app',
    measurementId: 'G-1L6XGE5M2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTT-cbDP__9h59va7x4rqxUu8ofUPJqs',
    appId: '1:855525575269:android:ef72fbf40c0dc85a83148c',
    messagingSenderId: '855525575269',
    projectId: 'student-management-app-c937e',
    storageBucket: 'student-management-app-c937e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgZlAjtznPgFdxM3sdl7l5HPf-dIZiZbE',
    appId: '1:855525575269:ios:48c8319deac3a84783148c',
    messagingSenderId: '855525575269',
    projectId: 'student-management-app-c937e',
    storageBucket: 'student-management-app-c937e.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgZlAjtznPgFdxM3sdl7l5HPf-dIZiZbE',
    appId: '1:855525575269:ios:48c8319deac3a84783148c',
    messagingSenderId: '855525575269',
    projectId: 'student-management-app-c937e',
    storageBucket: 'student-management-app-c937e.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQl6AFfSwDTGTsHnOs2yPuuzbrbMHH96c',
    appId: '1:855525575269:web:a5e8394b1de29c0483148c',
    messagingSenderId: '855525575269',
    projectId: 'student-management-app-c937e',
    authDomain: 'student-management-app-c937e.firebaseapp.com',
    storageBucket: 'student-management-app-c937e.firebasestorage.app',
    measurementId: 'G-5608HKCCJ1',
  );
}
